name: Debug Build

on: [push, pull_request]

jobs:
  build-debug:
    runs-on: windows-latest

    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

    steps:
      - name: Checkout and initialise
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Dalamud
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/latest.zip -OutFile ./latest.zip
          Expand-Archive -Path ./latest.zip ./dalamud

      - name: Restore project dependencies
        run: dotnet restore --verbosity normal

      - name: Build Debug
        run: dotnet build --no-restore --verbosity normal --configuration Debug

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: XIVAuras-debug-${{ github.sha }}
          path: |
            XIVAuras/bin/x64/Debug
            !XIVAuras/bin/x64/Debug/XIVAuras
